Fix highlighting in the questions of type select.
tmbo/questionary pull request #134
Opened 2021-07-05 06:59 UTC by MAD-py

issue #132 mentions an error in the highlighting of select type questions.

This error occurs when the default value is an object of type Choice because the condition being evaluated does not make a good comparison to know which option to highlight.

this is a quick, simple and functional fix that does not affect the rest of the operation.

2021-07-10 00:23 UTC, kiancross requested changes
This looks great - thank you. Ideally, the broken example given in #132 would be added as a test case, however, I think this is a difficult example to unit test so it can be left out.

I think the only problem remaining is that `default` can also be a `dict`. At the moment, this isn't handled correctly either, I don't think.

https://github.com/tmbo/questionary/blob/2979fb8c6404f69112e8ebf918f9a2b29a310b45/questionary/prompts/common.py#L191

We could probably leave that for another PR, as I imagine the use case of passing a `dict` is far lower than passing a `Choice`.

2021-07-10 00:27 UTC, kiancross submitted a review, later dismissed

2021-07-10 02:55 UTC, MAD-py commented
I agree with what you say, I'm going to look at the other case this weekend and try to get a solution

But as you say I think that the best way to do it would be to create a new PR.

2021-07-10 16:55 UTC, MAD-py commented
I have a question about the use of default for the library that goes hand in hand with the solution I presented for this PR.

default if it should be sensitive to the data type in a strict way.

Example:

`
c = Choice("Bar")
select("Choose something", ["Foo", c], default="Bar").ask()
`

in this example two possible answers are sent, one of type str and the other of type choice, the default is of type str but with the same value as the answer of type choice.

The doubt that arises to me is if this error should be the expected one or if really one should be able to do this.

Output:
![Captura de pantalla de 2021-07-10 11-53-51](https://user-images.githubusercontent.com/52325575/125170665-99a3bc80-e175-11eb-86e8-db5f6e09f79f.png)

2021-07-11 14:35 UTC, kiancross commented
The intention, as it stands, is for this to be an error. The `default` parameter is expected to identically match one of the `choices`. However, particularly for the case of passing a `dict`, this doesn't seem too nice.

I think there are a few aspects of the API that could be tidied up and perhaps this should be one of them.

2021-07-11 14:37 UTC, kiancross approved these changes

2021-07-11 14:37 UTC, merged

2021-07-12 00:25 UTC, MAD-py commented
I got it, so based on what you told me, in the next few days I will take a look at it and do some tests to see  how to improve the handling of the values set as dict.

I have just created an issue (#138) on the subject so we can continue talking about it.

thank you very much for clarifying my doubts and remember to close issue #132 that with the merge of this PR is ready.