fix tests for different versions of prompt-toolkit
tmbo/questionary pull request #222
Opened 2022-04-26 09:53 UTC by beliaev-maksim

**What is the problem that this PR addresses?**

there are some breaking changes in prompt-toolkit

`questionary` handles it well except tests part

**How did you solve it?**

fix tests for different versions
add CI matrix

**Checklist**

- [x] I have read the [Contributor's Guide](https://questionary.readthedocs.io/en/stable/pages/contributors.html#steps-for-submitting-code).
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-04-26 13:57 UTC, kiancross requested changes
Thanks for the PR.

Was there anything in particular that was broken, or is this just a general improvement?

2022-04-26 13:57 UTC, kiancross commented on tests/utils.py
> +def _execute_with_input_pipe(func):
```suggestion
def execute_with_input_pipe(func):
```

2022-04-26 13:57 UTC, kiancross commented on tests/utils.py
> +_prompt_toolkit_version = [int(v) for v in prompt_toolkit.VERSION]
```suggestion
prompt_toolkit_version_tuple = tuple([int(v) for v in prompt_toolkit.VERSION])
```

Now you can do

```python3
if prompt_toolkit_version_tuple < (3, 0, 29):
    pass
```

2022-04-26 14:25 UTC, beliaev-maksim commented on .github/workflows/continous-integration.yml
> +        promttoolkit: [3.*, 2.*, 3.0.19, 3.0.29]
we need to test versions like 3.0.3 as well, or we can drop support of `prompt-toolkit` v2 and pin to the >=3.0.29

2022-04-26 14:35 UTC, beliaev-maksim commented
@kiancross 
basically, tests will not run with new versions of the prompt toolkit, so, I think would be good to fix tests to validate it as well

2022-04-26 15:16 UTC, beliaev-maksim commented on .github/workflows/continous-integration.yml
> +        promttoolkit: [3.*, 2.*, 3.0.19, 3.0.29]
let's remove such tests for all OSs, otherwise it is overkill. I added them just on Linux, this primary check should be sufficient

2022-05-15 08:19 UTC, tmbo approved these changes
thanks a lot for the test improvements 🔥

2022-05-15 08:26 UTC, merged