Try to support prompt_toolkit >3.0.37
tmbo/questionary pull request #347
Opened 2023-12-30 12:26 UTC by FantasqueX

Currently one test will fail with latest prompt_toolkit(3.0.43). test_blank_line_fix will throw RuntimeError: no running event loop. By bisecting commit, the culprit is
https://github.com/prompt-toolkit/python-prompt-toolkit/commit/a7759969891c54ea56abfa286524cc301eedaf05. This commit replaces custom `get_event_loop` with `asyncio.get_event_loop`. The former will creator a new loop if `asyncio.get_running_loop` fails while the latter won't. I mimic the changes in the examples to use `asyncio.run` and the test passes. I'm not sure whether more changes are needed.

**What is the problem that this PR addresses?**

https://github.com/tmbo/questionary/issues/344

**How did you solve it?**

Use `asyncio.run` to make the test pass.

**Checklist**

- [x] I have read the [Contributor's Guide](https://questionary.readthedocs.io/en/stable/pages/contributors.html#steps-for-submitting-code).
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-12-30 12:28 UTC, FantasqueX commented
@kiancross Hi, could you please take a look at this? I'm not sure whether I have to do more except making all tests pass.

2024-01-26 07:57 UTC, FantasqueX commented
I've fixed code quality problem. Gently ping~

2024-03-03 13:14 UTC, florian6973 commented
Any update please?

2024-07-09 04:36 UTC, kiancross commented
@FantasqueX Please could you merge latest changes into this branch and then I can run the CI.

2024-07-09 16:24 UTC, FantasqueX commented
> @FantasqueX Please could you merge latest changes into this branch and then I can run the CI.

@kiancross Done :)

2024-07-17 10:10 UTC, kiancross reviewed
The CI is currently failing because there was a breaking change in `3.0.29`, which changed the return type of `create_pipe_input`. Prior to this version, it did not return a context manager.

https://github.com/prompt-toolkit/python-prompt-toolkit/commit/97ac51413f8d412599233fc3da44d4c7fc456f8c

Given we support these previous versions of `prompt_toolkit` (for reasons I am unaware of), I suppose some conditional logic needs to be added here?

2024-07-24 17:09 UTC, FantasqueX commented
@kiancross Hi, I have added some conditional logic and make CI happy. Could you please review it again :)

2024-07-24 22:43 UTC, kiancross requested changes

2024-07-24 22:43 UTC, kiancross commented on tests/prompts/test_common.py
> +            asyncio.run(run(inp))
I think you can do something like this:

```suggestion
    pipe_input = create_pipe_input()
    if prompt_toolkit_version < (3, 0, 29):
        pipe_input = pipe_input.create()

    with pipe_input as inp:
        asyncio.run(run(inp))
```

2024-07-24 22:51 UTC, kiancross approved these changes

2024-07-24 22:53 UTC, merged

2024-07-26 08:58 UTC, fijemax commented
Hello, can we tag a new version who is carrying this fix ?

2024-07-26 13:22 UTC, kiancross commented
I'll push a new version within the next week.

2024-09-20 13:20 UTC, superlevure commented
Hello, could we get a new release with this fix?