Removed check for choices if completer is present
tmbo/questionary pull request #52
Opened 2020-07-09 08:23 UTC by Zylvian

Had a problem supplying my own Completer, as I had to make a dummy list with a single value to get the check to pass. This commit should let people be able to supply **either** a completer or choices for the default completer.

2020-09-07 16:41 UTC, kiancross commented
@Zylvian Checks are failing because you need to run `black questionary` over the code, to ensure it is properly formatted.

2020-10-04 14:25 UTC, tmbo commented on questionary/prompts/autocomplete.py
> +
```suggestion
```

2020-10-04 14:25 UTC, tmbo approved these changes

2020-10-04 14:39 UTC, kiancross commented on questionary/prompts/autocomplete.py
```suggestion
```

2020-10-04 14:42 UTC, kiancross requested changes

2020-10-04 14:42 UTC, kiancross commented on questionary/prompts/autocomplete.py
> +
```suggestion

```

2020-10-04 14:42 UTC, kiancross commented on questionary/prompts/autocomplete.py
> +
```suggestion

```

2020-10-04 14:42 UTC, kiancross commented on questionary/prompts/autocomplete.py
```suggestion
```

2020-10-04 14:47 UTC, kiancross approved these changes

2020-10-04 14:47 UTC, merged