Fix double space between question and instructions in `confirm`
tmbo/questionary pull request #89
Opened 2020-11-24 20:40 UTC by SamSchott

At the moment, there are two spaces printer a question and the instructions (Y/n) or answer in a `confirm dialog`.  This PR removes one of those spaces.

If the double spaces are intentional, feel free to close.

2020-11-25 01:00 UTC, SamSchott commented
On a side note: I noticed somewhat inconsistent spacing for several dialogs:

* Text: single space between message and answer / result.
* Path: single space
* Select: two spaces
* Checkbox: two spaces
* Confirm: two spaces

Personally, I prefer a single space. But either way, it would be nice to be consistent. It looks a bit odd otherwise.

2020-11-26 05:25 UTC, kiancross commented
Thanks for the PR. @tmbo do you have any views on 1 space vs 2 spaces? If not I suppose we should just pick one or the other for consistency.

2020-12-01 11:15 UTC, tmbo commented
mhm no not, really I think either one works - but all in on consistency 🚀

2020-12-02 00:41 UTC, kiancross commented
@SamSchott Do you want to change the others to single spaces too before I merge this in?

2020-12-03 11:28 UTC, SamSchott commented
Done.

2020-12-03 16:47 UTC, kiancross requested changes
One more to remove here I think, then good to go.

https://github.com/tmbo/questionary/blob/146e320ebc1a5995fd2b7c6a0954d969396b3379/questionary/prompts/checkbox.py#L108

2020-12-03 16:52 UTC, SamSchott commented
I must have overlooked this one...

2020-12-03 17:20 UTC, kiancross approved these changes

2020-12-03 17:20 UTC, merged